 #*******************INICIO DEL CÓDIGO AUTO GENERADO ****************************
 
esphome:
  name: "sensor-nivel-agua"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[*****REEMPLAZAR CON SU PROPIO API KEY*****]" 

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-06A4Cb"
    password: "[*****REEMPLAZAR CON SU PROPIA CONTRASEÑA*****]"

captive_portal:

 #*******************FIN DEL CÓDIGO AUTO GENERADO ******************************


sensor:
  - platform: uptime
    name: "Tiempo en línea"

  - platform: adc
    pin: A0
    name: "Voltaje del Sensor"
    id: voltaje_sensor
    update_interval: 90s
    accuracy_decimals: 0
    internal: True
    filters:
      - multiply : 1000


  - platform : template
    name : "Porcentaje de agua"
    id: porcentaje_agua
    unit_of_measurement : "%"
    accuracy_decimals : 0
    update_interval : 90s
    lambda: |-
      if (id(voltaje_sensor).state >= 450){
        return 100;
      } else if (id(voltaje_sensor).state <= 315) {
        return 0;
      } else {
        return (((id(voltaje_sensor).state) - 315)*100) / (450-315);
      }    
